### ISSUE TITLE
Crash NullPointerException at co.mobiwise.library.GCMManager$1.onReceive(GCMManager.java:150)

### ISSUE THREAD

**Issue by elye** [iammert/FastGCM#3]
Hi Iammert

When using the library from ```com.github.iammert:FastGCM:0bf078c8ad```, I face the crash as below
```E/AndroidRuntime(11626): java.lang.NullPointerException
E/AndroidRuntime(11626): 	at co.mobiwise.library.GCMManager$1.onReceive(GCMManager.java:150)
E/AndroidRuntime(11626): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
E/AndroidRuntime(11626): 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)```

I'm suspecting it crash on ```mGcmListener.onDeviceRegisted(token);``` where ```mGcmListener.onDeviceRegisted``` is null.

The step I did was, open up the App (to register the device with GCM server). Then kill the App. After that send a notification. When the notification received, the crash happens. 

I checked the library code in the repository, looks like the bug could have been fixed? (e.g. there's a guard for Null Pointer in ```mGcmListerner``` before using it at line 148). To assure, I just copy out the entire library code directly instead of using it from ```com.github.iammert:FastGCM:0bf078c8ad```, then the crash no longer happens.

Perhaps the exported library need to be updated with your latest code? Hopes to hear from you.

Thanks!!
_Elye_

**Comment by iammert** [comment]
Thanks for detailed feedback. It is really weird because gcmmanager class is checking listener before notify it. Maybe it is because jitpack link has older version. I updated jitpack link. Can you check this one and tell me what happened? (I updated readme with updated jitpack)
```compile 'com.github.iammert:FastGCM:00e66c0931'```

**Comment by elye** [comment]
Hi Iammert. 
Cool! Just by pointing to the new updated library, no more crash. Thanks!!
Cheers!
_Elye_
